[[ROCmOpenCLRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb5aa1744e858beba3e3f00d0c67f606386a427c"
libc = "glibc"
os = "linux"

    [[ROCmOpenCLRuntime.download]]
    sha256 = "ad2a44cb9a412a77324140c67ba25f218c23e556a8c8e2caa5db4d0f56a32c29"
    url = "https://github.com/JuliaBinaryWrappers/ROCmOpenCLRuntime_jll.jl/releases/download/ROCmOpenCLRuntime-v4.0.0+1/ROCmOpenCLRuntime.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmOpenCLRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7a3dc8b763945639080e2f65a08ba789dd18eeb"
libc = "musl"
os = "linux"

    [[ROCmOpenCLRuntime.download]]
    sha256 = "aa479b9d886a9e812b90fa2be785509897491a3040fd7c65d438a1d06219fa3f"
    url = "https://github.com/JuliaBinaryWrappers/ROCmOpenCLRuntime_jll.jl/releases/download/ROCmOpenCLRuntime-v4.0.0+1/ROCmOpenCLRuntime.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"
