[[ROCmOpenCLRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ca2a28d9082bbbb0791571011ac3e1b0759ed4f"
libc = "glibc"
os = "linux"

    [[ROCmOpenCLRuntime.download]]
    sha256 = "c0a7fb6c313a8ca07be7a236c548391f80c4d0501766fd523e1a4b9fe996aee2"
    url = "https://github.com/JuliaBinaryWrappers/ROCmOpenCLRuntime_jll.jl/releases/download/ROCmOpenCLRuntime-v4.0.0+0/ROCmOpenCLRuntime.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmOpenCLRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13ecf733f729010cd5fe7e403cb465bced450087"
libc = "musl"
os = "linux"

    [[ROCmOpenCLRuntime.download]]
    sha256 = "876d7dfdedab654c7639d2933fb30503b22cab3ecfd57dbe90828ea9dcce3fc9"
    url = "https://github.com/JuliaBinaryWrappers/ROCmOpenCLRuntime_jll.jl/releases/download/ROCmOpenCLRuntime-v4.0.0+0/ROCmOpenCLRuntime.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"
