[[ROCmOpenCLRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a7b0c762e1bb7fe62d0b428caabb5a9afdf006c"
libc = "glibc"
os = "linux"

    [[ROCmOpenCLRuntime.download]]
    sha256 = "3429fe21187ccdf58039bd6b85db365bdaa0a2ee28c4fc42a7c4f4727d22280d"
    url = "https://github.com/JuliaBinaryWrappers/ROCmOpenCLRuntime_jll.jl/releases/download/ROCmOpenCLRuntime-v5.4.4+0/ROCmOpenCLRuntime.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmOpenCLRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65921fbd8f2c0d009d97a266a1ac8810b5dd99ed"
libc = "musl"
os = "linux"

    [[ROCmOpenCLRuntime.download]]
    sha256 = "1bd352b0d624a5086fcbf38aa66c1643ad354e006823c49f2103490fc8577210"
    url = "https://github.com/JuliaBinaryWrappers/ROCmOpenCLRuntime_jll.jl/releases/download/ROCmOpenCLRuntime-v5.4.4+0/ROCmOpenCLRuntime.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"
