[[ROCmOpenCLRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b6da8164e38b0f65fd9b632e4146839f2b032b2"
libc = "glibc"
os = "linux"

    [[ROCmOpenCLRuntime.download]]
    sha256 = "ecd9d1d010d8dac591b8957cc97ac6150590a6913f1ac5c00a62170ace27fa17"
    url = "https://github.com/JuliaBinaryWrappers/ROCmOpenCLRuntime_jll.jl/releases/download/ROCmOpenCLRuntime-v4.2.0+0/ROCmOpenCLRuntime.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmOpenCLRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ce974d7a51f0173512709e7d0e163d42f602434"
libc = "musl"
os = "linux"

    [[ROCmOpenCLRuntime.download]]
    sha256 = "f99a07b3b002c140b478330ac0d61ab006160eec5297270b8cabce3c4e9b503e"
    url = "https://github.com/JuliaBinaryWrappers/ROCmOpenCLRuntime_jll.jl/releases/download/ROCmOpenCLRuntime-v4.2.0+0/ROCmOpenCLRuntime.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
