# Autogenerated wrapper script for ROCmOpenCLRuntime_jll for x86_64-linux-musl-cxx11
export libOpenCL, libamdocl

using hsa_rocr_jll
using ROCmDeviceLibs_jll
using ROCmCompilerSupport_jll
using Libglvnd_jll
using Xorg_libX11_jll
using Xorg_xorgproto_jll
JLLWrappers.@generate_wrapper_header("ROCmOpenCLRuntime")
JLLWrappers.@declare_library_product(libOpenCL, "libOpenCL.so.1")
JLLWrappers.@declare_library_product(libamdocl, "libamdocl64.so")
function __init__()
    JLLWrappers.@generate_init_header(hsa_rocr_jll, ROCmDeviceLibs_jll, ROCmCompilerSupport_jll, Libglvnd_jll, Xorg_libX11_jll, Xorg_xorgproto_jll)
    JLLWrappers.@init_library_product(
        libOpenCL,
        "lib/libOpenCL.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libamdocl,
        "lib/libamdocl64.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
